---
version: 3.0

rpc:
  address: peer0.net0.mainnet
  port: 8334
  username: admin
  password: admin
shell:
output:
  path: ./out
# mode: once # once, block, duration, infinity
# blockCount: 6
# period: 5m
# duration: 1h
# type: testnet # testnet, simnet, mainnet, signet
