version: '3'

volumes:
  mainnet:

# 0 Note that you need to build docker image manually use Dockerfile. Follow docs/docker-compose.md
# 1 Note that you can add followings into hosts file to use dotest
# 172.16.0.20 peer0.net0.test.net

networks:
  bitlog_mainnet:
    ipam:
      config:
        - subnet: ${SUBNET_CIDR:-172.16.0.0/24}

services:
  mainnet:
    container_name: ${CONTAINER_NAME:-peer0.net0.mainnet}
    hostname: ${HOSTNAME:-peer0.net0.mainnet}
    image: ${IMAGE:-bitlog/btcd:latest}
    labels:
      service: bitlog_btcd
    # environment:
    #   -
    working_dir: /bitlog/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "9999"
        max-size: "1g"
    command: btcd
    volumes:
      - ${BTCD_ROOT_DIR}:/root/.btcd/
    ports:
      - ${PORT_PEER:-8333}:${PORT_PEER:-8333}
      - ${PORT_RPC:-8334}:${PORT_RPC:-8334}
    networks:
      bitlog_mainnet:
        ipv4_address: ${SUBNET_ADDRESS:-172.16.0.10}